server {
    listen 80;

    location /api/status {
        proxy_pass http://100.99.91.99:8000/public/status;
        proxy_set_header Host $host;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ =404;
    }
}
